name: Continuous integration
on:
  push:
    branches: [dev]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Pulling changes for testing
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.IP_ADDRESS }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd /var/www/zc_plugin_company_files
            git restore .
            git pull origin dev
            npm run install-setup
            npm run build:npm
            pm2 restart 0
            
 
